# This is a basic workflow to help you get started with Actions.

name: Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for the main branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: pyinstaller --name SRE-QR-Generator-Windows --onefile --windowed main.py

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/SRE-QR-Generator-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyInstaller
        run: pyinstaller --name SRE-QR-Generator-macOS --onefile --windowed main.py

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/SRE-QR-Generator-macOS.app
